[package]
name = "warp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.39.2", features = ["rt-multi-thread", "macros"] }
warp = "0.3.7"
